language: r
sudo: required

matrix:
  include:
    - os: linux
      r: release
      env: NOT_CRAN=true
    - os: linux
      r: devel
      env: NOT_CRAN=false

r_github_packages:
  - hadley/httr
  - jimhester/covr

before_install:
    - echo TRAITBASE_USER=$TRAITBASE_USER > .Renviron
    - echo TRAITBASE_PWD=$TRAITBASE_PWD >> .Renviron
    - cat .Renviron

after_success:
  - Rscript -e 'library(covr); codecov()'
